# hiihihi welcome to ChatMinigames, a lightweight, open-sourced and customizable plugin for chat minigames
# Source code: https://github.com/UwUAroze/ChatMinigames

# Config.yml:
# After making any changes, make sure to reload with /cmg reload
# If you severely fuck up, you can reset the config by deleting the file and reloading the config, or plugin.

# Formatting with colour codes:
# Mineraft colours, example: "Woah &cRed&r!!!"
# Hex codes, example: "Woah, a &#ff6e6eFancier Red&r!!"

########################################################################################################################

messages:
  # The message that will appear if a player tries to force start or use any other commands associated with ChatMinigames, if they do not have permission:
    no-permission: "&#ff6e6e⚠ &#ff7f6eYou aren't allowed to do this! smh!"

  # The message that will appear if a player attempts to force start a game without specifying one:
    no-game-specified: "&#ff6e6e⚠ &#ff7f6eSyntax: /forcestart <Random | Scramble | Rush | Math>"

  # The message that will appear if a player attempts to force start a game that does not exist:
    invalid-game: "&#ff6e6e⚠ &#ff7f6eThat game doesn't exist, dummy!"

  # The message that will appear if a player enters too many args while force starting:
    too-many-args: "&#ff6e6e⚠ &#ff7f6eThat's too many args weirdo."