########################################################################################################################

# hii welcome to ChatMinigames: a lightweight, open-sourced and customizable plugin for chat minigames
# Source code: https://github.com/UwUAroze/ChatMinigames

# Config.yml:
# After making any changes, make sure to reload with /cmg reload
# To reset the config, delete this file, then restart your server or /cmg reload.
# Default config: https://github.com/UwUAroze/ChatMinigames/tree/master/src/main/resources/config.yml

# Formatting:
# Hex (&#<hex code>) and regular colour codes (&<code>) are supported:
# Example: "Woah &cRed&r!!!"
# Hex example: "Woah, a &#ff6e6eFancier Red&r!!"

# Placeholders:
# Some configurable messages support placeholders, for instance the numbers in the math game; these will be clarified
# in comments surrounding the corresponding config options.

########################################################################################################################

# Comma separated list of words to be randomised and used in applicable minigames; namely Rush and Unscramble
# Spaces will be ignored.

wordList:
  "Attractive, Baguette, Bathtub, Bedrock, Broadcast, Brother, Ceiling, Character, Choke, Compartment, Competitive,
  Conclusion, Confession, Couple, Cucumber, Daddy, Defenestration, Diamond, Discombobulated, Duvet, Eggplant, Emerald,
  Extension, Fishing, Floor, Generator, Greeting, Hypothesis, Immortal, Improvement, Invasion, Iron, Journal, Knowledge,
  Legend, Marriage, Mommy, Multiplier, Nerd, Obsidian, Photosynthesis, Pillow, Prestige, Raid, Sister, Stick, Suck,
  Summer, Swallow, Transparent, Treat, Unique, Villager, Vomit, Winter"

########################################################################################################################

minigame-messages:
  starting-hover: # Text to be shown up on hovering over the game start message
    reactionTime: "&#ffd4e3&oPsst.. click me!"

  game-start: # Messages to broadcast when a specific game starts
    math: # Available placeholders: {num1}, {num2}, {operation}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - ""
      - "&#ffb3a6Correctly answer this the fastest to gain &#ff8787100 coins!"
      - "&#ffb3a6Equation: &#ff8787{num1}{operation}{num2}"
      - "&7&m                            "

    rush: # Available placeholders: {answer}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - ""
      - "&#ffb3a6Type the word the fastest for &#ff8787100 coins!"
      - "&#ffb3a6Word: &#ff8787{answer}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambled}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - ""
      - "&#ffb3a6Unscramble the word the fastest for &#ff8787100 coins!"
      - "&#ffb3a6Word: &#ff8787{scrambled}"
      - "&7&m                            "

    reactionTime: # No available placeholders.
    # PS: Extra space increases the clickable area for this minigame.
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Reaction Time"
      - "                                                                  "
      - "&#ffb3a6Click this message the fastest for &#ff8787100 coins!"
      - "&7&m                            "


  answered-correctly-broadcast: # Messages to broadcast for when a player completes a specific game
    math: # Available placeholders: {num1}, {num2}, {operation}, {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - "&#ffb3a6{player} correctly answered the equation in &#ff8787{elapsedTime}"
      - "&#ffb3a6Equation: &#ff8787{num1}{operation}{num2} = {answer}"
      - "&7&m                            "

    rush: # Available placeholders: {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - "&#ffb3a6{player} correctly typed the word in &#ff8787{elapsedTime}"
      - "&#ffb3a6Word: &#ff8787{answer}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambled}, {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - "&#ffb3a6{player} correctly answered in &#ff8787{elapsedTime}"
      - "&#ffb3a6The word was: &#ff8787{answer}"
      - "&7&m                            "

    reactionTime: # Available placeholders: {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Reaction Time"
      - ""
      - "&#ffb3a6{player} clicked the message in &#ff8787{elapsedTime}"
      - "&7&m                            "


  answered-correctly-private: # Private message to be sent to a player who completes a specific game
    math:
      - "&7&oCorrectly solved math problem, &#ffb3a6&o+100 Coins"

    rush:
      - "&7&oCorrectly typed word, &#ffb3a6&o+100 Coins"

    unscramble:
      - "&7&oCorrectly unscrambled word, &#ffb3a6&o+100 Coins"

    reactionTime:
      - "&7&oFirst to click, &#ffb3a6&o+100 Coins"

########################################################################################################################

misc-settings:
  case-sensitive: false # Should answer checking for unscramble/rush be case-sensitive?
  cancel-winning-answers: true # Should the player's message be cancelled (not be sent) if it was a correct answer?
  ignore-cancelled-messages: true # Should cancelled messages (eg: muted players) be ignored?

########################################################################################################################