# hiihihi welcome to ChatMinigames, a lightweight, open-sourced and customizable plugin for chat minigames
# Source code: https://github.com/UwUAroze/ChatMinigames

# Config.yml:
# After making any changes, make sure to reload with /cmg reload
# If you severely fuck up, you can reset the config by deleting the file and reloading the config, or plugin.

# Formatting with colour codes:
# Mineraft colours, example: "Woah &cRed&r!!!"
# Hex codes, example: "Woah, a &#ff6e6eFancier Red&r!!"

#
# Placeholders:
#
# For game start broadcasts:
# {mathNumber1} : the first number in a math equation (works in game-start-math or answered-correctly-math messages)
# {mathNumber2} : the second number in a math equation (works in game-start-math or answered-correctly-math messages)
# {mathAnswer} : the answer to a math equation (works in game-start-math messages)
# {mathOperator} : the operator in a math equation (works in game-start-math or answered-correctly-math messages)
#
# {elapsedTime} : a formatted timestamp of the time taken to complete a game (works in any answered-correctly messages)
# {player} : the player who answered (works in any answered-correctly messages, and any reward)

########################################################################################################################

# This list will be used for both unscramble and rush. Separate each word with a comma:
  wordList: 'Nerd, Broadcast, Swallow, Marriage, Bathtub, Couple, Knowledge, Transparent, Journal, Greeting, Attractive, Pillow, Hypothesis, Legend, Mommy, Daddy, Brother, Sister, Confession, Suck, Swallow, Vomit, Choke, Defenestration, Duvet, Baguette, Cucumber, Generator, Multiplier, Prestige, Photosynthesis, Character, Competitive, Unique, Stick, Fishing, Eggplant, Immortal, Bedrock, Obsidian, Iron, Diamond, Emerald, Villager, Conclusiveness, Discombobulated, Improvement, Extension, Compartment, Treat, Invasion, Raid, Summer, Winter, Ceiling, Floor'

rewards:
  # The command to execute when a player correctly answers a math equation
    math: 'addcoins {player} 100'

messages:
  # The broadcast for when a Math game starts:
    game-start-math:
    - "&7&m                            "
    - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
    - ""
    - "&#ffb3a6Correctly answer this the fastest to gain &#ff8787100 coins!"
    - "&#ffb3a6Equation: &#ff8787{mathNum1}{mathOperation}{mathNum2}"
    - "&7&m                            "

  # The broadcast for when a player correctly answers a math equation:
    answered-correctly-math-broadcast:
    - "&7&m                            "
    - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
    - "&#ffb3a6{player} correctly answered the equation in &#ff8787{elapsedTime}"
    - "&#ffb3a6Equation: &#ff8787{mathNum1}{mathOperation}{mathNum2} = {mathAnswer}"
    - "&7&m                            "

  # The private message to a player who correctly answers a math equation
    answered-correctly-math-private: "&7&oCorrectly answered math equation, &#ffb3a6&o+100 Coins"

  # Permission message for all ChatMinigame commands:
    no-permission: "&#ff6e6e⚠ &#ff7f6eYou aren't allowed to do this! smh!"

  # Message to be sent if a player attempts to force start a game without specifying one:
    no-game-specified: "&#ff6e6e⚠ &#ff7f6eSyntax: /forcestart <Random | Scramble | Rush | Math>"

  # Message to be sent if a player attempts to force start a game that does not exist:
    invalid-game: "&#ff6e6e⚠ &#ff7f6eThat game doesn't exist, dummy!"

  # Message to be sent if a player enters too many args while force starting:
    too-many-args: "&#ff6e6e⚠ &#ff7f6eThat's too many args weirdo."

misc:
  # Should a noteblock pling (minecraft:block.note_block.pling) play to players who correctly complete a minigame?
    play-noteblock-pling: true
    noteblock-volume: 1.0 # Any decimal between 0 and 1 (keep the .0)
    noteblock-pitch: 2.0 # Any decimal between 0 and 2 (keep the .0)