
########################################################################################################################

# hiihihi welcome to ChatMinigames, a lightweight, open-sourced and customizable plugin for chat minigames
# Source code: https://github.com/UwUAroze/ChatMinigames

# Config.yml:
# After making any changes, make sure to reload with /cmg reload
# If you severely fuck up, you can reset the config by deleting the file and reloading the config, or plugin.

# Formatting with hex and regular colour codes is supported:
# Example: "Woah &cRed&r!!!"
# Hex example: "Woah, a &#ff6e6eFancier Red&r!!"

########################################################################################################################

# This word list will be used for both unscramble and rush.
wordList:
  - 'Nerd'
  - 'Broadcast'
  - 'Swallow'
  - 'Marriage'
  - 'Bathtub'
  - 'Couple'
  - 'Knowledge'
  - 'Transparent'
  - 'Journal'
  - 'Greeting'
  - 'Attractive'
  - 'Pillow'
  - 'Hypothesis'
  - 'Legend'
  - 'Mommy'
  - 'Daddy'
  - 'Brother'
  - 'Sister'
  - 'Confession'
  - 'Suck'
  - 'Swallow'
  - 'Vomit'
  - 'Choke'
  - 'Defenestration'
  - 'Duvet'
  - 'Baguette'
  - 'Cucumber'
  - 'Generator'
  - 'Multiplier'
  - 'Prestige'
  - 'Photosynthesis'
  - 'Character'
  - 'Competitive'
  - 'Unique'
  - 'Stick'
  - 'Fishing'
  - 'Eggplant'
  - 'Immortal'
  - 'Bedrock'
  - 'Obsidian'
  - 'Iron'
  - 'Diamond'
  - 'Emerald'
  - 'Villager'
  - 'Conclusion'
  - 'Discombobulated'
  - 'Improvement'
  - 'Extension'
  - 'Compartment'
  - 'Treat'
  - 'Invasion'
  - 'Raid'
  - 'Summer'
  - 'Winter'
  - 'Ceiling'
  - 'Floor'

# Commands to execute when a player completes a chat minigame
# The "/" is already added onto the start
# Available placeholders: {player}
rewards:
  math: 'addcoins {player} 100'
  rush: 'addcoins {player} 100'
  unscramble: 'addcoins {player} 100'


messages:
  game-start: # Messages to broadcast when a specific game starts
    math: # Available placeholders: {mathNum1}, {mathNum2}, {mathOperation}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - ""
      - "&#ffb3a6Correctly answer this the fastest to gain &#ff8787100 coins!"
      - "&#ffb3a6Equation: &#ff8787{mathNum1}{mathOperation}{mathNum2}"
      - "&7&m                            "

    rush: # Available placeholders: {rushWord}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - ""
      - "&#ffb3a6Type the word the fastest for &#ff8787100 coins!"
      - "&#ffb3a6Word: &#ff8787{rushWord}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambledWord}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - ""
      - "&#ffb3a6Unscramble the word the fastest for &#ff8787100 coins!"
      - "&#ffb3a6Word: &#ff8787{scrambledWord}"
      - "&7&m                            "


  answered-correctly-broadcast: # Messages to broadcast for when a player completes a specific game
    math: # Available placeholders: {mathNum1}, {mathNum2}, {mathOperation}, {mathAnswer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - "&#ffb3a6{player} correctly answered the equation in &#ff8787{elapsedTime}"
      - "&#ffb3a6Equation: &#ff8787{mathNum1}{mathOperation}{mathNum2} = {mathAnswer}"
      - "&7&m                            "

    rush: # Available placeholders: {rushWord}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - "&#ffb3a6{player} correctly typed the word in &#ff8787{elapsedTime}"
      - "&#ffb3a6Word: &#ff8787{rushWord}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambledWord}, {actualWord}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - "&#ffb3a6{player} correctly answered in &#ff8787{elapsedTime}"
      - "&#ffb3a6The word was: &#ff8787{actualWord}"
      - "&7&m                            "


  answered-correctly-private: # Private message to be sent to a player who completes a specific game
    math: "&7&oCorrectly answered math equation, &#ffb3a6&o+100 Coins"
    rush: "&7&oCorrectly typed word, &#ffb3a6&o+100 Coins"
    unscramble: "&7&oCorrectly unscrambled word, &#ffb3a6&o+100 Coins"


  other:
  # Permission message for all ChatMinigame commands:
    no-permission: "&#ff6e6e⚠ &#ff7f6eYou aren't allowed to do this! smh!"
  # Message to be sent if a player attempts to force start a game without specifying one:
    no-game-specified: "&#ff6e6e⚠ &#ff7f6eSyntax: /cmg forcestart <Random | Unscramble | Rush | Math>"
  # Message to be sent if a player attempts to force start a game that does not exist:
    invalid-game: "&#ff6e6e⚠ &#ff7f6eThat game doesn't exist, dummy!"
  # Message to be sent if a player enters too many args while force starting:
    too-many-args: "&#ff6e6e⚠ &#ff7f6eThat's too many args weirdo."

misc:
  # Should a noteblock pling (minecraft:block.note_block.pling) play to players who correctly complete a minigame?
    play-noteblock-pling: true
    noteblock-volume: 1.0 # Any decimal between 0 and 1 (keep the .0)
    noteblock-pitch: 2.0 # Any decimal between 0 and 2 (keep the .0)

  # Should answer checking for unscramble/rush be case sensitive?
    case-sensitive:
      unscramble: false
      rush: false

  # Should messages be cancelled if a player correctly answers?
    cancel-messages: true