name: Chat-Minigames
version: '${project.version}'
main: me.aroze.chatminigames.ChatMinigames
api-version: 1.18
authors: [ Aroze ]
description: A lightweight, open-sourced and customizable plugin for chat minigames
website: aroze.me
commands:
  chatminigames:
    aliases: [ cmg ]